// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhblUkT01oDuq9QmJF1mubbCQHXKRz2bs',
    appId: '1:351413649224:web:444ee96d12439c1db57d7d',
    messagingSenderId: '351413649224',
    projectId: 'flutter-firebase-ec9d5',
    authDomain: 'flutter-firebase-ec9d5.firebaseapp.com',
    storageBucket: 'flutter-firebase-ec9d5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVXXgTcCm6VZ9PcSSQbuIzc8peJ3vCpdU',
    appId: '1:351413649224:android:b80d1bcc2cfd2e05b57d7d',
    messagingSenderId: '351413649224',
    projectId: 'flutter-firebase-ec9d5',
    storageBucket: 'flutter-firebase-ec9d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsJxHHQAq-StQ3ac7a9b_Sp0O44h2MTsA',
    appId: '1:351413649224:ios:515995c12e625b41b57d7d',
    messagingSenderId: '351413649224',
    projectId: 'flutter-firebase-ec9d5',
    storageBucket: 'flutter-firebase-ec9d5.firebasestorage.app',
    iosBundleId: 'com.example.ifmdApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsJxHHQAq-StQ3ac7a9b_Sp0O44h2MTsA',
    appId: '1:351413649224:ios:515995c12e625b41b57d7d',
    messagingSenderId: '351413649224',
    projectId: 'flutter-firebase-ec9d5',
    storageBucket: 'flutter-firebase-ec9d5.firebasestorage.app',
    iosBundleId: 'com.example.ifmdApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhblUkT01oDuq9QmJF1mubbCQHXKRz2bs',
    appId: '1:351413649224:web:88732fe36e23d69bb57d7d',
    messagingSenderId: '351413649224',
    projectId: 'flutter-firebase-ec9d5',
    authDomain: 'flutter-firebase-ec9d5.firebaseapp.com',
    storageBucket: 'flutter-firebase-ec9d5.firebasestorage.app',
  );
}
